#setwd("D:/immersion/spotify mood")
#devtools::install_github("hrbrmstr/streamgraph")
library(dplyr)
library(tibble)
library(streamgraph)
library(lubridate)
library(readr)
spmood1 <- read.csv(file= "combined_spmood.csv")
spmood1tib <- as_tibble(spmood1)
